defaults:
  actions:
    backport:
      assignees:
        - "{{ author }}"

pull_request_rules:
  - name: backport patches to v23 branch
    conditions:
      - base=osmo/v0.37.4
      - label=S:backport/v23
    actions:
      backport:
        branches:
          - osmo-v23/v0.37.4
  - name: backport patches to v24 branch
    conditions:
      - base=osmo/v0.37.4
      - label=S:backport/v24
    actions:
      backport:
        branches:
          - osmo-v24/v0.37.4
  - name: backport patches to v25 branch
    conditions:
      - base=osmo/v0.37.4
      - label=S:backport/v25
    actions:
      backport:
        branches:
          - osmo-v25/v0.37.4
